name: food_ordering_app
description: A Flutter app for ordering food.
publish_to: "none" # Remove this line if you plan to publish the package.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.7.1
  google_fonts: ^6.2.1 # Update to the latest version
  provider: ^6.0.0 # Check for a compatible version
  http: ^1.1.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  table_calendar: ^3.0.9

flutter:
  uses-material-design: true
